"""COMMENT ON statements for genai_poc schema - business glossary metadata."""

SCHEMA = "genai_poc"

TABLE_COMMENTS = {
    "origination_currentversion": "General mortgage origination information.",
    "originationproperty_currentversion": "Mortgage origination property information like property address, property type etc.",
    "originationborrower_currentversion": "Mortgage origination borrower, co-borrower, co-mortgager specific information.",
}

# column_name -> comment (from Excel Tab 2)
COLUMN_COMMENTS = {
    "origination_currentversion": {
        "loannumber": "Loan Number",
        "version": "Loan Version",
        "organizationcode": "Company - Users Organization Code",
        "originationdate": "Mortgage or Loan Application Date",
        "baseloanamount": "Total Loan Amt (w/ MIP/FF)",
        "occupancytype": "Occupancy Type",
        "loanpurposetype": "Loan Purpose. Sample Values - Purchase,Cash-Out Refinance,NoCash-Out Refinance",
        "channel": "Loan Info Channel",
        "loanprogramname": "Loan Program",
        "mortgagetype": "Loan Type. Sample Values - Conventional,FHA,VA",
        "gserefinancepurposetype": "Loan Info Refi Purpose",
        "ltv": "Freddie Mac Loan To Value (LTV)",
        "combinedltv": "Comb Loan to Value (CLTV)",
        "requestedinterestratepercent": "Interest Rate",
        "loanamortizationtermmonths": "Term (Mos)",
        "purchasepriceamount": "Purchase Price",
        "loanamortizationtype": "Amort Type",
        "secondsubordinateamount": "Sub Fin Second Mtg Loan Amt",
        "applicationtakenmethodtype": "Application Taken By",
        "loanstatusdate": "Current Status Date",
        "borrowerrequestedloanamount": "Loan Amount",
        "interviewername": "Interviewer Name",
        "repurchasedate": "Repurchase Date",
        "repurchasecostamount": "Repurchase Cost",
        "conformingjumbo": "Conforming Loan Indicator",
        "lenderchannel": "Lender Channel",
        "pmiindicator": "Private Mortgage Insurance Indicator",
        "nmlsloanoriginatorid": "NMLS Loan Originator ID",
        "loansubmittedtobrokerdate": "Date Loan submitted to Broker",
        "dtiattimeofctc": "DTI at time of CTC",
        "isdigitalmortgage": "Loan originated from Digital Mortgage system",
        "brokerloanfundeddate": "Funded Date for Broker Loans",
        "loanfolder": "Loan Folder",
        "filestartername": "Team Member name who played the role of File Starter",
        "balloonindicator": "Amort Type Balloon",
        "lienprioritytype": "Lien Position",
        "prepaymentpenaltyindicator": "Prepayment Penalty",
        "subsequentrateadjustmentmonthscount": "Loan Info ARM First Period Change",
        "loandocumentationtype": "Fannie Mae Loan Doc Type Code",
        "firstchargeamount": "CREDIT CARD AMOUNT",
        "closingdate": "Closed Date",
        "transdetailslockdate": "Trans Details Lock Date",
        "constructionmethodtype": "ULDD Construction Method Type",
        "atrloantype": "ATR QM - Eligibility - Ability-to-Repay Loan Type",
        "gseagencyqmstatusinterestonly": "ATR QM - Eligibility - GSE/Agency Qualified Mortgage - Interest Only",
        "gseagencyqmstatusnegativeamortization": "ATR QM - Eligibility - GSE/Agency Qualified Mortgage - Negative Amortization",
        "gseagencyqmstatusballoonpayment": "ATR QM - Eligibility - GSE/Agency Qualified Mortgage - Balloon Payment",
        "gseagencyqmstatusprepaymentpenalty": "ATR QM - Eligibility - GSE/Agency Qualified Mortgage - Prepayment Penalty",
        "statementcreditdenialotherdesc1": "Denial Other - Other 1 Descr",
        "statementcreditdenialotherdesc2": "Denial Other - Other 2 Descr",
        "tsumunpaidbalance": "Sub Fin Additional Mtgs",
        "tpocompanyname": "TPO Company Name",
        "valoancreditscore": "VA Loan Summ Credit Score",
        "fundeddate": "Funded Date",
        "milestonename": "Milestone Stage Name",
        "istestloan": "This is a test loan",
        "agencypooluploaddate": "Agency Pool Upload Date",
        "lqa": "LQA",
        "lastcompletedmilestone": "Last Finished Milestone",
        "entityid": "Entity Identifier",
        "poolnumber": "Pool Number",
        "commitmentnumber": "Commitment Number",
        "currentapplicationindex": "Current Application Index",
        "isliabilitysuspensereason": "Reason for Suspense - Liabilities",
        "loanoriginatorfirstname": "VP First Name",
        "loanoriginatorlastname": "VP Last Name",
        "paidloid": "Final / Paid LO Code",
        "paidloname": "LO to receive credit",
        "adtrack": "Ad Track / Direct Tracking String",
        "firsttimehomebuyerindicator": "First Time Home Buyer",
        "principalandinterestmonthlypaymentamount": "Principal and Interest Monthly Payment Amount",
        "proposedmaturityyears": "Trans Details Loan Term",
        "proposedtotalhousingexpense": "Expenses Proposed Total Housing",
        "proposedothermortgagesamount": "Expenses Proposed Other Payment",
        "proposedmortgageinsuranceamount": "Expenses Proposed Mortgage Insurance",
        "proposedrealestatetaxesamount": "Expenses Proposed Taxes",
        "proposedduesamount": "Expenses Proposed HOA",
        "proposedhazardinsuranceamount": "Expenses Proposed Hazard Insurance",
        "freddiemacnoappraisalmaf": "Freddie Mac No-Appraisal MAF",
        "incomeexpirationvalidationindicator": "Income Expiration Validation Checkbox",
        "leadsource": "Rate Lead Source",
        "filestartdate": "Tracking - File Started Milestone Date",
        "creditreportordereddate": "Credit Report Ordered Date",
        "borrowercount": "Borrower Count",
        "selfemployed": "Self Employed",
        "brokerloanclosedate": "Close Date for Broker Loans",
        "complianceteamcomments": "Compliance Team Comments",
        "legalholddate": "Date of Legal Hold",
        "legalholdreleasedate": "Date of Legal Hold Release",
        "batchdelete": "Batch Delete",
        "velocifyleadid": "L360 (Velocify) Lead ID",
        "adversesubmissiondate": "Adverse Submission Date",
        "adverseactiontype": "Adverse Action Type on the new adverse action form",
        "appraisalexpirationdate": "Appraisal Expiration Date",
        "creditexpirationdate": "Credit Expiration Date",
        "ficofirstpulleddate": "Date the first credit report was pulled",
        "preapprovalordereddate": "Pre-Approval Ordered Date",
        "respaapplicationdate": "RESPA Application Date",
        "submittedtoprocessingdate": "Submitted to Processing Date",
        "undiscountedrate": "UnDiscounted Rate",
        "productdescription": "Product Description",
        "loanfeaturesotherindicator": "Loan Features Other Indicator",
        "freddiemacincomebaseddeedrestrictions": "Freddie Mac Income Based Deed Restrictions",
        "guaranteefeeborrowerpaidamount": "Fees Line 1010 Guarantee Fee Borr",
        "refinanceoriginalcreditorindicator": "ATR QM - Non-Standard to Standard Refinance Eligibility - Refinance with Original Creditor",
        "commercialloanproducttype": "Commercial Loan Product Type",
        "commercialloanproducttypeother": "Commercial Loan Other Product Type",
        "costcenterchargebacklo": "LO Responsible for CC chargebacks",
        "leadsourcebrco": "BRCO Lead Source",
    },
    "originationborrower_currentversion": {
        "loannumber": "Loan Number [FK: origination_currentversion.loannumber]",
        "applicationnumber": "Application Index",
        "borrowernumber": "Sequence Number",
        "version": "Loan Version",
        "firstname": "First Name",
        "lastnamewithsuffix": "Last Name with Suffix",
        "lastname": "Last Name",
        "ageatapplication": "Age at application",
        "experiancreditscore": "Experian FICO",
        "ssn": "SSN",
        "hmdagendertype": "Sex Male/Female",
        "birthdate": "DOB",
        "equifaxscore": "Equifax BEACON",
        "transunionscore": "TransUnion Empirica",
        "hmdaethnicitytype": "Ethnicity",
        "hmdaamericanindianindicator": "Race American Indian",
        "hmdaasianindicator": "Race Asian",
        "hmdaafricanamericanindicator": "Race Black",
        "hmdapacificislanderindicator": "Race Native Hawaiian",
        "hmdawhiteindicator": "Race White",
        "hmdanotprovidedindicator": "Race Info not provided",
        "hmdanotapplicableindicator": "Race Not Applicable",
        "hmdanocoapplicantindicator": "No Co-applicant Indicator",
        "isethnicitybasedonvisual": "Was the Ethnicity of the Borrower collected on the basis of visual observation or surname?",
        "isracebasedonvisual": "Was the Race of the Borrower collected on the basis of visual observation or surname?",
        "issexbasedonvisual": "Was the Sex of the Borrower collected on the basis of visual observation or surname?",
        "hmdaotherhispaniclatinoorigin": "Other Hispanic Latino Origin",
        "hmdaamericanindiantribe": "American Indian Tribe",
        "hmdaotherasianrace": "Other Asian Race",
        "hmdaotherpacificislanderrace": "Other Pacific Islander Race Origin",
        "applicationtakenmethodtype": "Application Taken By",
        "hmdamexicanindicator": "Mexican Indicator",
        "hmdapuertoricanindicator": "Puerto Rican Indicator",
        "hmdacubanindicator": "Cuban Indicator",
        "hmdahispaniclatinootheroriginindicator": "Other Hispanic Latino Origin Indicator",
        "hmdaasianindianindicator": "Asian Indian Indicator",
        "hmdachineseindicator": "Chinese Indicator",
        "hmdafilipinoindicator": "Filipino Indicator",
        "hmdajapaneseindicator": "Japanese Indicator",
        "hmdakoreanindicator": "Korean Indicator",
        "hmdavietnameseindicator": "Vietnamese Indicator",
        "hmdaasianotherraceindicator": "Other Asian Race Indicator",
        "hmdanativehawaiianindicator": "Native Hawaiian Indicator",
        "hmdaguamanianorchamorroindicator": "Guamanian or Chamorro Indicator",
        "hmdasamoanindicator": "Samoan Indicator",
        "hmdapacificislanderotherindicator": "Other Pacific Islander Indicator",
        "hmdagendertypefemaleindicator": "Female Indicator",
        "hmdagendertypemaleindicator": "Male Indicator",
        "hmdagendertypedonotwishindicator": "Gender Type Do Not Wish Indicator",
        "hmdagendertypenotapplicableindicator": "Gender Type Not Applicable Indicator",
        "hmdaethnicitydonotwishindicator": "Borr Ethnicity Do Not Wish Indicator",
        "hmdaethnicityhispaniclatinoindicator": "Borr Hispanic or Latino Indicator",
        "hmdaethnicitynothispaniclatinoindicator": "Borr Not Hispanic or Latino Indicator",
        "hmdaethnicitynotapplicableindicator": "Borr Ethnicity Not Applicable Indicator",
        "hmdaethnicityinfonotprovided": "Borr Ethnicity Information Not Provided Indicator",
        "hmdaraceinfonotprovided": "Borr Race Information Not Provided",
        "hmdasexinfonotprovided": "Borr Sex Information Not Provided",
        "hmdaracedonotwishprovideindicator": "Borr Race I do not wish to provide this information",
        "underwritingriskassesstype": "AUS Tracking - Latest Submission - Underwriting Risk Assess Type",
        "ausrecommendation": "AUS Tracking - Latest Submission - AUS Recommendation",
        "timeoncurrentjobtermyears": "Borr Yrs on Job",
        "timeoncurrentjobtermmonths": "Borr Mos on Job",
        "timeonpreviousjobtermyears": "Previous Employment Yrs",
        "timeonpreviousjobtermmonths": "Previous Employment Mos",
        "currentresidencedurationtermyears": "Borr Own # Yrs",
        "currentresidencedurationtermmonths": "Borr Own # Mos",
        "previousresidencedurationtermyears": "Borr Previous Addr # Yrs",
        "previousresidencedurationtermmonths": "Borr Previous Addr # Mos",
        "hmda2creditscorefordecisionmaking": "Borr Credit Score for Decision Making",
        "hmda2creditscoringmodel": "Borr Credit Scoring Model",
        "ficoscore": "FICO Score",
        "middlename": "Middle Name",
        "suffix": "Suffix",
        "emailaddress": "Email Address",
        "mailingaddressline1": "Mailing Address Line 1",
        "mailingaddressline2": "Mailing Address Line 2",
        "mailingaddresscity": "Mailing Address City",
        "mailingaddressstate": "Mailing Address State",
        "mailingaddresszip": "Mailing Address Zip Code",
        "currentaddressline1": "Current Address Line 1",
        "currentaddressline2": "Current Address Line 2",
        "currentaddresscity": "Current Address City",
        "currentaddressstate": "Current Address State",
        "currentaddresszip": "Current Address Zip Code",
        "homephonenumber": "Home Phone Number",
        "hmdaethnicityreported": "HMDA Ethnicity Reported Fields",
        "hmdaracereported": "HMDA Race Reported Fields",
    },
    "originationproperty_currentversion": {
        "loannumber": "Loan Number [FK: origination_currentversion.loannumber]",
        "version": "Loan Version",
        "streetaddress": "Subject Property Street",
        "cityname": "Subject Property City",
        "statecode": "Subject Property State",
        "zipcode": "Subject Property Zip",
        "numberofunits": "Subject Property # Units",
        "propertyrightstype": "Subject Property Estate Held",
        "appraisedvalueamount": "Subject Property Appraised Value",
        "estimatedvalueamount": "Subject Property Est Value",
        "gsepropertytype": "Subject Property Type Fannie Mae",
        "propertyusagetype": "Subject Property Use Type",
        "propertyvaluationdate": "ULDD - Property Valuation Effective Date",
        "county": "Subject Property County",
        "lotacres": "Property Info # of Lot Acres",
        "commercialloanproperty": "Commercial Loan Property",
        "commercialpropertytype": "Commercial Property Type",
        "commercialpropertytypeother": "Commercial Property Type Other",
    },
}
